CInema/Controllers/QueryController.cs
using Cinema.Domain.Db;
using Cinema.Models;
using Cinema.Models.Query;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Oracle.ManagedDataAccess.Client;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.Controllers
{
    public class QueryController : Controller
    {
        private readonly CinemaDbContext _context;
        private readonly string ConnectionString;
        public QueryController(CinemaDbContext context, IConfiguration Configuration)
        {
            _context = context;
            ConnectionString = Configuration.GetConnectionString("OracleDBConnection");
        }

        [HttpGet]
        public IActionResult BoxOffice()
        {
            var boxOffices = _context.BoxOffices.Select(x => new BoxOfficeViewModel
            {
                Film = _context.Films.First(g => g.Kod == x.KodFilm).Name,
                TotalSum = x.TotalSum,
                Date = x.DateBoxOffice,
            }).ToArray();
            ViewData["TableName"] = "Кассовые сборы";
            ViewData["Headers"] = new string[] { "Фильм", "Сумма", "Дата" };
            ViewData["TableData"] = boxOffices;
            return View();
        }

        [HttpGet]
        public IActionResult ListFilms()
        {
            var russiaCode = _context.Countries.First(x => x.Name == "Россия").Kod;
            var films = _context.Films.Where(x => x.StartDate.Year == 2021 && x.CountryKod == russiaCode).Select(x => new FilmViewModel
            {
                Id = x.Kod,
                Country = _context.Countries.
                                        Where(c => c.Kod == x.CountryKod).
                                        Select(c => new IdName()
                                        {
                                            Id = c.Kod,
                                            Name = c.Name
                                        }).First(),
                Genre = _context.Genres.
                                        Where(g => g.Kod == x.GenreKod).
                                        Select(g => new IdName()
                                        {
                                            Id = g.Kod,
                                            Name = g.Name
                                        }).
                                        First(),
                Name = x.Name,
                Rating = _context.Ratings.
                                        Where(r => r.Kod == x.RatingKod).
                                        Select(r => new IdName()
                                        {
                                            Id = r.Kod,
                                            Name = r.Name
                                        }).
                                        First(),
                StartDate = x.StartDate,
                Studio = _context.FilmStudios.
                                        Where(s => s.Kod == x.StudioKod).
                                        Select(s => new IdName()
                                        {
                                            Id = s.Kod,
                                            Name = s.Name
                                        }).
                                        First(),
                TimeDuration = x.TimeDuration
            }).AsEnumerable();
            ViewData["TableName"] = "Список фильмов, вышедших в текущем году в России";
            ViewData["Headers"] = new string[] { "Фильм", "Дата", "Страна" };
            ViewData["TableData"] = films;
            return View();
        }

        [HttpGet]
        public IActionResult ListRole()
        {
            OracleConnection con = new();
            con.ConnectionString = ConnectionString;
            con.Open();

            OracleCommand cmd = con.CreateCommand();
            cmd.CommandType = CommandType.Text;
            cmd.CommandText = "select kino.PACKAGE__P.spisokemp from dual";
            List<List<string>> response = new();
            var lenth = 1;
            if (lenth > 0)
            {
                OracleDataReader reader = cmd.ExecuteReader();

                while (reader.Read())
                {
                    response.Add(new List<string>());
                    for (int i = 0; i < lenth; i++)
                    {
                        response[^1].Add(reader.GetString(i));
                    }
                }
            }
            else
            {
                cmd.ExecuteNonQuery();
            }

            con.Close();

            var result = response[0][0].Split("haha").ToArray();
            result = result.Take(result.Length - 1).ToArray();
            ViewData["TableName"] = "Фильмы, в которых режиссер является одновременно " +
                "исполнителем главной роли";
            ViewData["Headers"] = new string[] { "Фильм - Режиссер"};
            ViewData["TableData"] = result;
            return View();
        }

        [HttpGet]
        public IActionResult StatisticsGenre()
        {
            var russiaCode = _context.Countries.First(x => x.Name == "Россия").Kod;
            var films = _context.Films.Select(x => x).ToArray();

            var genres = films.GroupBy(x => x.GenreKod).Select(x => new 
            {
                Genre = x.Key,
                RuFilm = films.Where(f => f.GenreKod == x.Key && f.CountryKod == russiaCode).Count(),
                Count = x.Count()
            }).Select(x => new StatOnGenre
            {
                Genre = _context.Genres.First(g => g.Kod == x.Genre).Name,
                RusAmount = x.RuFilm,
                ForreignAmount = x.Count - x.RuFilm
            }).AsEnumerable();
            ViewData["TableName"] = "Статистика по жанрам";
            ViewData["Headers"] = new string[] { "Жанр", "Кол-во фильмов снятых в России", "Кол-во фильмов снятых в др. странах" };
            ViewData["TableData"] = genres;
        
            return View();
        }

        [HttpGet]
        public IActionResult ApproximateAge(IdName model)
        {
            ViewData["Employes"] = _context.Employees.Select(x => new IdName()
            {
                Id = x.Kod,
                Name = x.FIO(),
                }).AsEnumerable();

            if (model.Id == 0)
            {
                model.Id = (ViewData["Employes"] as IEnumerable<IdName>).First().Id;
            }
            OracleConnection con = new();
            con.ConnectionString = ConnectionString;
            con.Open();

            OracleCommand cmd = con.CreateCommand();
            cmd.CommandType = CommandType.Text;
            cmd.CommandText = "SELECT PACKAGE__P.AGE(" + model.Id.ToString() +") FROM DUAL";

            OracleDataReader reader = cmd.ExecuteReader();
            string response = "";
            while (reader.Read())
            {
                response += reader.GetString(0);
            }

            ViewData["Table"] = response;

            ViewData["TableName"] = "Примерный возраст";
            ViewData["Headers"] = new string[] { "Возраст" };
            con.Close();

            return View(model);
        }

        [HttpGet]
        public IActionResult FilmTime(IdName model)
        {
            ViewData["Films"] = _context.Films.Select(x => new IdName()
            {
                Id = x.Kod,
                Name = x.Name,
            }).AsEnumerable();
            if (model.Id == 0)
            {
                model.Id = (ViewData["Films"] as IEnumerable<IdName>).First().Id;
            }
            OracleConnection con = new();
            con.ConnectionString = ConnectionString;
            con.Open();

            OracleCommand cmd = con.CreateCommand();
            cmd.CommandType = CommandType.Text;
            cmd.CommandText = "SELECT PACKAGE__P.TIME_FILM(" + _context.Films.First(x=> x.Kod == model.Id).TimeDuration.ToString() + ") FROM DUAL";

            OracleDataReader reader = cmd.ExecuteReader();
            string response = "";
            while (reader.Read())
            {
                response += reader.GetString(0);
            }

            ViewData["Table"] = response;

            ViewData["TableName"] = "Строка продолжительности";
            ViewData["Headers"] = new string[] { "Продолжительность" };
            con.Close();

            return View(model);
        }
        [HttpGet]
        public IActionResult Fio(IdName model)
        {
            ViewData["Employes"] = _context.Employees.Select(x => new IdName()
            {
                Id = x.Kod,
                Name = x.FIO(),
            }).AsEnumerable();

            if (model.Id == 0)
            {
                model.Id = (ViewData["Employes"] as IEnumerable<IdName>).First().Id;
                model.Name = (ViewData["Employes"] as IEnumerable<IdName>).First().Name;
            }

            OracleConnection con = new();
            con.ConnectionString = ConnectionString;
            con.Open();

            OracleCommand cmd = con.CreateCommand();
            cmd.CommandType = CommandType.Text;
            cmd.CommandText = "SELECT PACKAGE__P.FULLNAME(" + model.Id.ToString() + ") FROM DUAL";

            OracleDataReader reader = cmd.ExecuteReader();
            string response = "";
            while (reader.Read())
            {
                response += reader.GetString(0);
            }

            ViewData["Table"] = response.Replace("..",".");

            ViewData["TableName"] = "Строка ФИО";
            ViewData["Headers"] = new string[] { "ФИО" };

            con.Close();

            return View(model);
        }

        public IActionResult PotentiaGet(DateFromTo dates)
        {
            if (dates.From != DateTime.MinValue)
            {

                OracleConnection con = new();
                con.ConnectionString = ConnectionString;
                con.Open();

CInema/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject ISignIn SignInManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../css/style.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&family=Playfair+Display&display=swap" rel="stylesheet">
    <title>Cinema</title>
</head>


<body>
    <header class="header">
        <div class="container">
            <div class="header_inner">
                <div class="header_logo">Реестр кинофильмов</div>

                <nav class="nav__link">
                    @if (SignInManager.IsSignedIn())
                    {
                        @if (SignInManager.IsAdmin())
                        {

                            @await Html.PartialAsync("_LayoutTable")

                            @await Html.PartialAsync("_LayoutDictionary")
                            @await Html.PartialAsync("_LayoutQuery")
                            <a class="nav_link" href="/Cinema/FormReport">Документ</a>

                            <a class="nav_link" href="/User/Logout">Выход</a>
                        }
                        else if (SignInManager.IsOperator())
                        {

                            @await Html.PartialAsync("_LayoutTable")

                            @await Html.PartialAsync("_LayoutDictionary")

                            <a class="nav_link" href="/User/Logout">Выход</a>
                        }
                    }



                </nav>
            </div>
        </div>
    </header>
    <main class="main">
        @RenderBody()
    </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    <script src="http://code.jquery.com/jquery-2.0.2.min.js"></script>

</body>
</html>

CInema/Views/Shared/_LayoutDictionary.cshtml
<div class="dropdown">

    <a class="dropbtn" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Справочники</a>
    <div class="dropdown-content">
        <a class="dropdown-content__link" asp-controller="Dictionary" asp-action="EmployeeTypes">Должности с.группы</a>

        <a class="dropdown-content__link" asp-controller="Dictionary" asp-action="Genre">Жанры</a>

        <a class="dropdown-content__link" asp-controller="Dictionary" asp-action="FilmStudio">Киностудии</a>

        <a class="dropdown-content__link" asp-controller="Dictionary" asp-action="Rating">Рейтинг</a>

        <a class="dropdown-content__link" asp-controller="Dictionary" asp-action="Countries">Страны</a>

    </div>

</div>

CInema/Views/Shared/_LayoutQuery.cshtml
<div class="dropdown">

    <a class="dropbtn" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Запросы</a>
    <div class="dropdown-content">
        <a class="dropdown-content__link" asp-controller="Query" asp-action="BoxOffice">Кассовые сборы</a>

        <a class="dropdown-content__link" asp-controller="Query" asp-action="ListFilms">Вышедшие фильмы</a>

        <a class="dropdown-content__link" asp-controller="Query" asp-action="ListRole">Роли в фильмах</a>

        <a class="dropdown-content__link" asp-controller="Query" asp-action="StatisticsGenre">Статистика жанров</a>

        <a class="dropdown-content__link" asp-controller="Query" asp-action="PotentiaGet">Доход</a>

        <a class="dropdown-content__link" asp-controller="Query" asp-action="Fio">ФИО</a>

        <a class="dropdown-content__link" asp-controller="Query" asp-action="ApproximateAge">Возраст</a>

        <a class="dropdown-content__link" asp-controller="Query" asp-action="FilmTime">Продолжительность</a>

    </div>

</div>

CInema/Views/Shared/_LayoutTable.cshtml
<div class="dropdown">

    <a class="dropbtn" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Таблицы</a>
    <div class="dropdown-content">
        <a class="dropdown-content__link" asp-controller="Cinema" asp-action="FilmsEmp">Актеры-режиссеры</a>

        <a class="dropdown-content__link" asp-controller="Cinema" asp-action="SessionFilms">Сеансы</a>

        <a class="dropdown-content__link" asp-controller="User" asp-action="AllUsers">Пользователи</a>

        <a class="dropdown-content__link" asp-controller="Cinema" asp-action="Films">Фильмы</a>

        <a class="dropdown-content__link" asp-controller="Cinema" asp-action="Employee">Съемочная группа</a>

    </div>

</div>

CInema/Views/Shared/_LoginDictionary.cshtml
    <div class="dropdown">


        <div class="dropdown-content">
            <a class="dropdown-content__link" asp-controller="Account" asp-action="Index">Должности</a>

            <a class="dropdown-content__link" asp-controller="Account" asp-action="Index">Жанры</a>

            <a class="dropdown-content__link" asp-controller="Account" asp-action="Index">Киностудии</a>

            <a class="dropdown-content__link" asp-controller="User" asp-action="Logout">Рейтинг</a>

            <a class="dropdown-content__link" asp-controller="Account" asp-action="Index">Страны</a>

        </div>

    </div> 

CInema/Views/Shared/_LoginLayout.cshtml
@{
    Layout = "_Layout";
}

<body>
    <main class="main__intro" role="main">
        @RenderBody()
    </main>
</body>

@section Scripts {
    @RenderSection("Scripts", false)

    <script type="text/javascript">
        $().ready(function () {
            setTimeout(function () {
                // after 1000 ms we add the class animated to the login/register card
                $('.card').removeClass('card-hidden');
            }, 700)
        });
    </script>
}